[package]
name = "kt"
version = "0.1.0"
authors = ["xi gua <tomato.stao@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "~2.32"
